student:
  name: 我是Springboot的属性配置文件
  text: 1234
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    url: jdbc:mysql://localhost:3306/ssm?useSSL=false
    username: root
    password: 123Aa.
    driver-class-name: com.mysql.jdbc.Driver
